### PR TITLE
use state and newState as return from Update funcs

### PR DESCRIPTION
**Pull request by conorhastings**

### CODE REVIEW

**Comment by jamesplease** [comment]
Thanks for putting this together, @conorhastings ! This fixes the issue with state, but there's still a problem with side effects. I have an idea for how that can be fixed, which I can make a PR for in a bit.

I'll write out the problem and solution I have in mind, too: the `sideEffects` array in state gets wiped if you return an `Update()` from `init`, as the behavior of `useReducer` is that the return value from `init` _replaces_ existing state, and the return value of `Update` is an object of the form `{ state }`

After thinking more about it, one solution that came to me is splitting out [this logic](https://github.com/conorhastings/use-reducer-with-side-effects/blob/6d619f28c31d14396e05f1380e18769adfa3fc47/src/index.js#L35-L45) into a standalone function, perhaps something called `mergeState(prevState, changes)`.

Then you could write an `init` in this lib that uses that new function before returning. To explain what I mean in code form, [these lines](https://github.com/conorhastings/use-reducer-with-side-effects/blob/6d619f28c31d14396e05f1380e18769adfa3fc47/src/index.js#L54-L61) could become something like:

```js
const [{ state, sideEffects }, dispatch] = useReducer(
  finalReducer(reducer),
  {
    state: initialState,
    sideEffects: []
  },
  (state) => {
    let changes;
    if (typeof init === 'function') {
      changes = init(state);
    }

    return {
      ...state,
      ...changes
    };
  }
);
```

I'll put together a PR that implements this in a bit for you to review :v:

**Comment by conorhastings** [comment]
Yeah that was my initial thought as well but thought perhaps I didn’t understand the issue enough, sounds cool though

**Comment by conorhastings** [comment]
my otheer idea was since finalReducer has access to state grab side effects and fallover

**Comment by conorhastings** [comment]
since the docs mention init as a case for resetting to initial state -- would we wantto unqueue side effects as well? in which case simple spread wouldn't work

**Comment by jamesplease** [comment]
> would we wantto unqueue side effects as well? in which case simple spread wouldn't work

Good question...I’m not sure right now. I’ll have to think more about it 🤔

**Comment by conorhastings** [comment]
my initial inclination is yes, (return to . a 0 state) but not sure

**Comment by jamesplease** [comment]
I think I agree!

**Comment by conorhastings** [comment]
closed inf avor of #19

**Pull request closed without merging**
